services:
  subscriber:
    healthcheck:
      disable: true
    labels:
      traefik.enable: "true"
      traefik.hostname: subscriber
    environment:
      GATEWAY_SYSTEM_NAME: subscriber
      GATEWAY_PUBLIC_HTTP_PORT: 80
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: subscriber.localtest.me
    networks:
      - default
      - proxy

  publisher:
    healthcheck:
      disable: true
    labels:
      traefik.enable: "true"
      traefik.hostname: publisher
    environment:
      GATEWAY_SYSTEM_NAME: publisher
      GATEWAY_PUBLIC_HTTP_PORT: 80
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: publisher.localtest.me
    networks:
      - default
      - proxy

  broker:
    healthcheck:
      disable: true
    labels:
      traefik.enable: "true"
      traefik.hostname: broker
      traefik.http.services.broker.loadbalancer.server.port: "8088"
    environment:
      GATEWAY_SYSTEM_NAME: broker
      GATEWAY_PUBLIC_HTTP_PORT: 80
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: broker.localtest.me
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    external: true
    name: proxy
